### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by saharasharlis** [Epochi/uport_jekyll#5]
Sunku uzdeti ta pranesima, kad cookius renkam? :)

**Comment by Epochi** [comment]
radau nete

> Might be nice to know, you no longer need to place the noticifation if you only use Google Analytics (you had to because GA uses a cookie to check for returning visitors) and cookies specific for the website. Because of this, most small common websites don't need a niticifation to the user.
> 
> The reason GA ís allowed, is because they don't track you from site to site, only if you come back. This is considered acceptable because it is basic information which is useful for a webmaster and not privacy invasive for visitors. These cookies are available for the visited domain only and therefor seen as first party.

**Comment by saharasharlis** [comment]
cool! :)
